<?php $helper = Mage::helper('baua') ?>
<?php if($helper->isActive()): ?>
    <!-- BEGIN GOOGLE UNIVERSAL ANALYTICS CODE {literal} -->
    <script type="text/javascript">
    <?php echo $helper->generateCurrencyInit() ?>

    <?php echo $helper->generateProductImpressions() ?>
    <?php echo $helper->generatePromoImpressions() ?>

    <?php echo $helper->getAction() ?>
    ga('send', 'pageview');

    <?php echo $helper->generateProductClickEvents() ?>
    <?php echo $helper->generatePromoClickEvents() ?>
    </script>
    <!-- {/literal} END GOOGLE UNIVERSAL ANALYTICS CODE -->
<?php endif ?>
